"""
Django settings for site_constructor project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import json

from decouple import config

from pathlib import Path

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#-)q&i(0@0ox-f8%@&2zc%0d!^q$qtg##b4cpxj1_4&3yjp5!d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = config('ALLOWED_HOSTS' ,default=[
    '*',  # Укажите порт, на котором работает ваш фронтенд
], cast=json.loads)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'constructor',
    'rest_framework',
    'corsheaders',
    'rest_framework.authtoken'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ]
}

# APPEND_SLASH=False

CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS' ,default=[
    "http://localhost:5173",  # Укажите порт, на котором работает ваш фронтенд
], cast=json.loads)

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'site_constructor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'site_constructor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DATABASE_NAME', default='site-constructor2'),
        'USER': config('DATABASE_USER', default='postgres'),
        'PASSWORD': config('DATABASE_PASSWORD', '12345'),
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static media (CSS, JavaScript, images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CONTENT_SETTINGS = {
  "header": {
    "sample1": {
      "content": {
        "title0": "Надзаголовок",
        "title1": "Заголовок",
        "title2": "Описание",
        "img1": "/content-img-sample1.png"
      }
    },
    "sample2": {
      "content": {
        "title0": "Надзаголовок",
        "title1": "Заголовок",
        "title2": "Описание"
      },
    },
    "sample3": {
      "content": {
        "title1": "Заголовок",
        "title2": "Описание"
      },
    },
    "sample4": {
      "content": {
        "title1": "Заголовок",
        "title2": "Описание",
        "img1": "/sample-icon2.jpg",
        "img2": "/sample-icon1.jpg"
      }
    }
  },
  "text": {
    "sample1": {
      "content": {
        "title0": "Заголовок",
        "text0": "Текст"
      },
    },
    "sample2": {
      "content": {
        "title0": "Заголовок",
        "text0": "Текст"
      },
    },
    "sample3": {
      "content": {
        "title0": "Заголовок",
        "text0": "Текст1",
        "text1": "Текст2"
      },
    },
    "sample4": {
      "content": {
        "title0": "Заголовок",
        "text0": "Всегда, когда провожу секции, смотрю не на конечный результат, а на ход размышлений. Можно выучить все типы задач, прийти, решить все заготовленные интервьюером задачи за 10 минут и молчать, но это не совсем то, что хочется видеть! Живой ум, поток мыслей, желание рассказать и обсудить своё решение — это то, что хочется видеть в первую очередь. Конечно, есть фактор волнения, который заставляет вас быстрее «закончить» всё это. Но и с ним можно бороться — просто решайте больше, не сдавайтесь даже после неудачных попыток, и тогда удача будет на вашей стороне."
      },
    },
    "sample5": {
      "content": {
        "text0": "Всегда, когда провожу секции, смотрю не на конечный результат, а на ход размышлений. Можно выучить все типы задач, прийти, решить все заготовленные интервьюером задачи за 10 минут и молчать, но это не совсем то, что хочется видеть! Живой ум, поток мыслей, желание рассказать и обсудить своё решение — это то, что хочется видеть в первую очередь. Конечно, есть фактор волнения, который заставляет вас быстрее «закончить» всё это. Но и с ним можно бороться — просто решайте больше, не сдавайтесь даже после неудачных попыток, и тогда удача будет на вашей стороне."
      },
    },
    "sample6": {
      "content": {
        "text0": "Всегда, когда провожу секции, смотрю не на конечный результат, а на ход размышлений. Можно выучить все типы задач, прийти, решить все заготовленные интервьюером задачи за 10 минут и молчать, но это не совсем то, что хочется видеть! Живой ум, поток мыслей, желание рассказать и обсудить своё решение — это то, что хочется видеть в первую очередь. Конечно, есть фактор волнения, который заставляет вас быстрее «закончить» всё это. Но и с ним можно бороться — просто решайте больше, не сдавайтесь даже после неудачных попыток, и тогда удача будет на вашей стороне.",
        "text1": "Всегда, когда провожу секции, смотрю не на конечный результат, а на ход размышлений. Можно выучить все типы задач, прийти, решить все заготовленные интервьюером задачи за 10 минут и молчать, но это не совсем то, что хочется видеть! Живой ум, поток мыслей, желание рассказать и обсудить своё решение — это то, что хочется видеть в первую очередь. Конечно, есть фактор волнения, который заставляет вас быстрее «закончить» всё это. Но и с ним можно бороться — просто решайте больше, не сдавайтесь даже после неудачных попыток, и тогда удача будет на вашей стороне.",
        "text2": "Всегда, когда провожу секции, смотрю не на конечный результат, а на ход размышлений. Можно выучить все типы задач, прийти, решить все заготовленные интервьюером задачи за 10 минут и молчать, но это не совсем то, что хочется видеть! Живой ум, поток мыслей, желание рассказать и обсудить своё решение — это то, что хочется видеть в первую очередь. Конечно, есть фактор волнения, который заставляет вас быстрее «закончить» всё это. Но и с ним можно бороться — просто решайте больше, не сдавайтесь даже после неудачных попыток, и тогда удача будет на вашей стороне."
      },
    },
    "sample7": {
      "content": {
        "title0": "Заголовок",
        "text0": "Текст1",
        "text1": "Текст2",
        "text2": "Текст3",
        "text3": "Текст4"
      },
    },
    "sample8": {
      "content": {
        "title0": "Заголовок",
        "text0": "Текст1",
        "text1": "Текст2",
        "text2": "Текст3",
        "text3": "Текст4"
      },
    },
    "sample9": {
      "content": {
        "title0": "Заголовок",
        "text0": "Текст1",
        "text1": "Текст2",
        "text2": "Текст3",
        "text3": "Текст4"
      },
    },
    "sample10": {
      "content": {
        "title0": "Заголовок",
        "text0": "Текст1",
        "text1": "Текст2",
        "text2": "Текст3",
        "text3": "Текст4"
      },
    }
  },
  "gallery": {
    "sample1": {
      "content": {
        "img1": "none",
        "img2": "none",
        "img3": "none"
      },
    },
    "sample2": {
      "content": {
        "img1": "none",
        "img2": "none"
      },
    },
    "sample3": {
      "content": {
        "img1": "none",
        "img2": "none",
        "img3": "none",
        "img4": "none",
        "img5": "none",
        "img6": "none",
        "isGrid": True
      },
    },
    "sample4": {
      "content": {
        "img1": "none",
        "img2": "none",
        "img3": "none",
        "img4": "none",
        "img5": "none",
        "isInfinite": True
      },
    },
    "sample5": {
      "content": {
        "img1": "none"
      },
    }
  },
  "button": {
    "sample1": {
      "content": {
        "text": "Кнопка",
        "link": "#"
      },
    },
    "sample2": {
      "content": {
        "text": "Кнопка",
        "link": "#"
      },
    },
    "sample3": {
      "content": {
        "text": "Кнопка",
        "link": "#"
      },
    },
    "sample4": {
      "content": {
        "text": "Кнопка",
        "link": "#"
      },
    },
    "sample5": {
      "content": {
        "text": "Кнопка",
        "link": "#"
      },
    },
    "sample6": {
      "content": {
        "text": "Кнопка",
        "link": "#"
      },
    },
    "sample7": {
      "content": {
        "text": "Кнопка",
        "link": "#"
      },
    },
    "sample8": {
      "content": {
        "text": "Кнопка",
        "link": "#"
      },
    }
  },
  "contacts": {
    "sample1": {
      "content": {
        "title0": "Контакты",
        "link0": "#",
        "link1": "#",
        "link2": "#"
      },
    },
    "sample2": {
      "content": {
        "title0": "Контакты",
        "title1": "+7 (909) 000 00 00",
        "title2": "IvanovIvan2000@gmail.com",
        "title3": "г. Екатеринбург, ул. Мира, 19"
      },
    },
    "sample3": {
      "content": {
        "link0": "#",
        "link1": "#",
        "link2": "#",
        "isBlack": True
      },
    },
    "sample4": {
      "content": {
        "link0": "#",
        "link1": "#",
        "link2": "#",
        "isBlack": True,
        "withMail": True
      },
    },
    "sample5": {
      "content": {
        "title0": "Контакты",
        "title1": "+7 (909) 000 00 00",
        "title2": "IvanovIvan2000@gmail.com",
        "title3": "г. Екатеринбург, ул. Мира, 19",
        "withMap": True
      },
    }
  },
  "video": {
    "sample1": {
      "content": {
        "video": "none"
      },
    },
    "sample2": {
      "content": {
        "videoLink": "none"
      },
    }
  }
}