# Generated by Django 5.2 on 2025-04-24 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('name', models.CharField()),
                ('state', models.CharField(choices=[('open', 'Опубликована'), ('close', 'Закрыта'), ('delete', 'Удалена')])),
                ('date_create', models.DateTimeField()),
                ('date_update', models.DateTimeField(null=True)),
                ('image', models.ImageField(null=True, upload_to='media/images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(unique=True)),
                ('password_hash', models.CharField()),
                ('role', models.CharField(choices=[('redactor', 'Редактор')])),
                ('first_name', models.CharField(null=True)),
                ('second_name', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SampleUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relation', models.CharField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='constructor.sample')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='constructor.user')),
            ],
        ),
    ]
