# Generated by Django 5.2 on 2025-05-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='1', max_length=150, unique=True),
        ),
    ]
