# Generated by Django 5.2 on 2025-05-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='data'
        ),
        migrations.AddField(
            model_name='sample',
            name='data',
            field=models.BinaryField(),
        ),
    ]
