# Generated by Django 5.2 on 2025-05-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_alter_sample_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='data',
            field=models.TextField(),
        ),
    ]
