# Generated by Django 5.2 on 2025-05-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0005_alter_sample_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='state',
            field=models.CharField(choices=[('open', 'Опубликована'), ('close', 'Закрыта'), ('delete', 'Удалена'), ('temp', 'Шаблон')]),
        ),
        migrations.AlterField(
            model_name='sampleuser',
            name='relation',
            field=models.CharField(choices=[('Создатель', 'creator')]),
        ),
    ]
