# Generated by Django 5.2 on 2025-05-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0007_alter_sampleuser_user_id_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='sample',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
