# Generated by Django 5.2 on 2025-06-09 08:38

from django.db import migrations, models

def temp_close(apps, schema_editor):
    Sample = apps.get_model('constructor', 'Sample')
    Samples = Sample.objects.all()
    for obj in Samples:
        if obj.state == 'temp':
            obj.is_template = True
            obj.state = 'close'
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0008_image_alter_sample_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(temp_close),
        migrations.AlterField(
            model_name='sample',
            name='state',
            field=models.CharField(choices=[('open', 'Опубликована'), ('close', 'Закрыта'), ('delete', 'Удалена')]),
        ),
    ]
